-- Create table for storing sensor logs
create table public.sensor_readings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  water_level float not null,
  rainfall_intensity int not null,
  status text not null,
  battery_voltage float
);

-- Enable Row Level Security (RLS) so data is safe
alter table public.sensor_readings enable row level security;

-- Create a policy that allows anyone (or your API) to insert data
create policy "Enable insert for API" 
on public.sensor_readings for insert 
with check (true);

-- Create a policy that allows the Dashboard to read data
create policy "Enable read access for all users" 
on public.sensor_readings for select 
using (true);

-- Enable realtime for live dashboard updates
alter publication supabase_realtime add table public.sensor_readings;