-- 1. Create a table to queue SMS commands from the Admin
create table public.sms_queue (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  message_body text not null,
  status text default 'pending',
  triggered_by uuid references auth.users
);

-- 2. Create a generic "Profiles" table to handle roles
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  role text default 'community'
);

-- 3. Enable Row Level Security
alter table public.sms_queue enable row level security;
alter table public.profiles enable row level security;

-- POLICY: Only authenticated users can queue SMS
create policy "Auth Users can queue SMS" on public.sms_queue for insert to authenticated with check (true);

-- POLICY: ESP32 can update the queue (to mark as 'sent')
create policy "ESP32 update queue" on public.sms_queue for update using (true);

-- POLICY: Anyone can read the queue
create policy "ESP32 read queue" on public.sms_queue for select using (true);

-- POLICY: Users can read their own profile
create policy "Users can read own profile" on public.profiles for select using (auth.uid() = id);

-- POLICY: Users can insert their own profile
create policy "Users can insert own profile" on public.profiles for insert with check (auth.uid() = id);